<?php

namespace App\Enums;

enum ResponseCode: string
{
    // Success codes
    case SUCCESS = 'REGISTRO EXITOSO';
    case LOGIN_SUCCESS = 'LOGIN EXITOSO';
    case LOGOUT_SUCCESS = 'SESION CERRADA EXITOSAMENTE';
    case DATA_LOADED = 'DATOS CARGADOS EXITOSAMENTE';
    case DATA_UPDATED = 'DATOS ACTUALIZADOS EXITOSAMENTE';
    case DATA_DELETED = 'DATOS ELIMINADOS EXITOSAMENTE';
    case PASSWORD_RESET = 'CONTRASEÑA RESTABLECIDA EXITOSAMENTE';
    case PASSWORD_CHANGED = 'CONTRASEÑA CAMBIADA EXITOSAMENTE';
    case TOKEN_REFRESHED = 'TOKEN REFRESCADO EXITOSAMENTE';
    case EMAIL_SENT = 'CORREO ENVIADO EXITOSAMENTE';
    case FILE_UPLOADED = 'ARCHIVO SUBIDO EXITOSAMENTE';
    case FILE_DELETED = 'ARCHIVO ELIMINADO EXITOSAMENTE';
    case RESOURCE_CREATED = 'RECURSO CREADO EXITOSAMENTE';
    case RESOURCE_UPDATED = 'RECURSO ACTUALIZADO EXITOSAMENTE';
    case RESOURCE_DELETED = 'RECURSO ELIMINADO EXITOSAMENTE';

    // Error codes
    case UNAUTHORIZED = 'NO AUTORIZADO';
    case FORBIDDEN = 'ACCESO DENEGADO';
    case NOT_FOUND = 'RECURSO NO ENCONTRADO';
    case VALIDATION_ERROR = 'ERROR DE VALIDACION';
    case SERVER_ERROR = 'ERROR DE SERVIDOR';
    case REGISTRATION_ERROR = 'ERROR DE REGISTRO';
    case LOGIN_ERROR = 'ERROR DE INICIO DE SESION';
    case INVALID_CREDENTIALS = 'CREDENCIALES INVALIDAS';
    case INVALID_TOKEN = 'TOKEN INVALIDO';
    case EXPIRED_TOKEN = 'TOKEN EXPIRADO';
    case INVALID_REQUEST = 'SOLICITUD INVALIDA';
    case DUPLICATE_ENTRY = 'REGISTRO DUPLICADO';
    case FILE_ERROR = 'ERROR AL PROCESAR ARCHIVO';
    case DATABASE_ERROR = 'ERROR DE BASE DE DATOS';
    case NETWORK_ERROR = 'ERROR DE CONEXION';
    case EMAIL_ERROR = 'ERROR AL ENVIAR CORREO';
    case PASSWORD_ERROR = 'ERROR AL PROCESAR CONTRASEÑA';
    case RESOURCE_ERROR = 'ERROR AL PROCESAR RECURSO';
    case QUOTA_EXCEEDED = 'CUOTA EXCEDIDA';
    case MAINTENANCE_MODE = 'SISTEMA EN MANTENIMIENTO';
    case RATE_LIMIT_EXCEEDED = 'LIMITE DE SOLICITUDES EXCEDIDO';
} 